language: node_js
node_js:
  - "node"
 
matrix:
  include:
    - os: linux
      before_install:
      - sudo add-apt-repository ppa:ethereum/ethereum -y
      - sudo apt-get update
      - sudo apt-get install build-essential -y
      - sudo apt-get install gcc g++ libssl-dev libudev-dev pkg-config
 
install:
  - bash ./bin/travis-install.sh
 
script:
  - bash ./bin/test.sh
