language: node_js
node_js:
  - 10
sudo: false

matrix:
  include:
    - os: linux
 
install:
  - npm install
  - npx ganache-cli --gasLimit 8000000 2> /dev/null 1> /dev/null & 
 
script:
  - sleep 5 # to make sure ganache-cli is up and running before compiling
  - set -e
  - rm -rf build
  - npx truffle compile
  - npx truffle migrate --reset --network development
  - npx truffle test
  - kill -9 $(lsof -t -i:8545)
  - npx truffle run coverage
  - cat coverage/lcov.info | npx coveralls
