language: node_js
node_js:
  - 10
 
matrix:
  include:
    - os: linux
      before_install:
      - sudo apt-get update
      - sudo apt-get install build-essential -y
      - sudo apt-get install gcc g++ libssl-dev libudev-dev pkg-config
 
install:
  - npm install
  - npm install -g truffle 
  - npx ganache-cli --gasLimit 8000000 2> /dev/null 1> /dev/null & 
 
script:
  - sleep 5 # to make sure ganache-cli is up and running before compiling
  - set -e
  - rm -rf build
  - truffle compile
  - truffle migrate --reset --network development
  - truffle test
  - kill -9 $(lsof -t -i:8545)
  - truffle run coverage
  - cat coverage/lcov.info | npx coveralls
